[package]
name = "directories"
version = "0.1.0"
edition = "2021"
authors = [ "Lut99" ]
description = "A niche little crate that simplifies creating large hardcoded directory structures."


[dependencies]
